### ISSUE TITLE
PlaceHolderAPI

### ISSUE THREAD

**Issue by AFink** [MeLays/MTTT#10]
PlaceholderAPI got updated -> error when registering placeholders, I got it fixed by using 2.4.0 instead of 2.4.4

https://github.com/PlaceholderAPI/PlaceholderAPI/releases

**Comment by phiph-s** [comment]
Resuming development for a bugfix update
Added to TODO

**Comment by phiph-s** [comment]
Done in 4.0.0 (relased soon)
