### ISSUE TITLE
Problem with the tester

### ISSUE THREAD

**Issue by CoolLord22** [MeLays/MTTT#2]
Hi there, my server IP is SlimeyPlayz.dynu.com and I'm having some issues with the tester. I think I've set it up properly, but when someone enters it, it does nothing. Please help!

**Comment by phiph-s** [comment]
Did you set also the tester.outer and tester.inner Locations ? (/ttt setlocation)

**Comment by CoolLord22** [comment]
I've set both inner and outer, but in /tester check the Optional location tester comes up as false...

**Comment by CoolLord22** [comment]
Is there a minimum number of players needed for the tester to work? Or can it be with just 2 players?

**Comment by phiph-s** [comment]
This can be set in the config.yml ...
Did you marked all the Blocks and the area ?

**Comment by CoolLord22** [comment]
As far as I'm aware everything's set up

Portal:
  enabled: true
  min: 2
  game:
    x: -1251.49007131727
    y: 25.0625
    z: 312.5169148578436
    pitch: 4.358515
    yaw: -358.7818
    world: TTT
  spec:
    x: -1251.5715367556402
    y: 45.0
    z: 312.45021823774493
    pitch: 90.0
    yaw: -0.8380127
    world: TTT
  back:
    x: -1228.5395790681714
    y: 4.0
    z: 311.57447418225075
    pitch: 3.0219707
    yaw: -269.12988
    world: TTT
  tester_data:
    blocks:
      f052964a-edbf-4c1c-8fd2-3e6fba4d6fa1:
        x: -1314.0
        y: 18.0
        z: 338.0
        world: TTT
      3465161c-1fb2-40ed-af62-e1c8877e485b:
        x: -1314.0
        y: 15.0
        z: 338.0
        world: TTT
      0a6ae4f3-2cb4-438c-958d-754fdf270de2:
        x: -1313.0
        y: 17.0
        z: 338.0
        world: TTT
      5a2b4e32-96b5-4813-b1a0-f81c903805f7:
        x: -1315.0
        y: 17.0
        z: 338.0
        world: TTT
      49754c62-fa78-46bc-9f17-3e1d6aee60a9:
        x: -1314.0
        y: 17.0
        z: 342.0
        world: TTT
    corner_small:
      x: -1318.0
      y: 20.0
      z: 318.0
      world: TTT
    corner_big:
      x: -1252.0
      y: 26.0
      z: 347.0
      world: TTT
  sign:
    set: true
    x: -1231.0
    y: 5.0
    z: 312.0
    world: TTT

**Comment by phiph-s** [comment]
Hm did you also add an Button to the blocks ?
