### ISSUE TITLE
I Can't Download it

### ISSUE THREAD

**Issue by DonSnake** [MeLays/MTTT#8]
Hi,
excuse me for the disturb but i can't download your resource.
When i try to downloading it by clicking "Download via external ec..." on spigot, i'm brought to you site but there is an error.

Forbidden
You don't have permission to access /rp/docs/download.php on this server.

**Comment by phiph-s** [comment]
Let me check that, thank you.

**Comment by phiph-s** [comment]
Works again. I'm sorry
